### ISSUE TITLE
Close this repository. thank you.

### ISSUE THREAD

**Issue by ybs32** [ybs32/TweetMate-for-Android#104]
**Summary:**
Close the application in accordance with Twitter's policy.

**Tasks:**
- [x] Announce the end of it in the app.
- [ ] Deactivate all functions of the app.
- [ ] Archive repository or delete? -> T.B.D
